name: Bug Report - Windows Applications - Intel Arc & Iris Xe Graphics
description: Report issues in your non-game applications, or Windows itself, with Intel ARC Graphics & Iris Xe drivers.
labels: 'Info: Needs Replication'
assignees: 'Bryce-7995'
body:
  - type: markdown
    attributes:
      value: |
        **Note: Once submitted, you can edit some of its fields, like checkboxes, directly, ie you don't need to use the Edit button**
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Checklist [README]
      description: "Please take a moment to review this checklist before completing the form."
      options:
        - label: Device is not undervolted nor overclocked
          required: true
        - label: Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
          required: true
        - label: Application is not cracked, modded and use the latest patch
          required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label:  Application [Required]
      description: "Full name of the application"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Processor / Processor Number [Required]
    validations:
      required: true
  - type: input
    attributes:
      label: Graphic Card [Required]
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: GPU Driver Version [Required]
      options:
        - label: '31.0.101.4644'
        - label: '31.0.101.4578'
        - label: '31.0.101.4577'
        - label: '31.0.101.4576'
        - label: '31.0.101.4575'
        - label: '31.0.101.4514'
        - label: '31.0.101.4502'
        - label: '31.0.101.4499'
        - label: '31.0.101.4382'
        - label: '31.0.101.4369'
        - label: '31.0.101.4335'
        - label: '31.0.101.4314'
        - label: '31.0.101.4311'
        - label: '31.0.101.4257'
        - label: '31.0.101.4255'
        - label: '31.0.101.4148'
        - label: '31.0.101.4146'
        - label: '31.0.101.4125'
        - label: '31.0.101.4123'
        - label: '31.0.101.4091'
        - label: '31.0.101.4090'
        - label: '31.0.101.4034'
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Rendering API [Required]
      options:
        - label: Vulkan
        - label: OpenGL
        - label: DirectX12
        - label: DirectX11
        - label: DirectX10
        - label: DirectX9
        - label: Not applicable
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Windows Build Number [Required]
      options:
        - label: Windows 11 22H2
        - label: Windows 11 21H2
        - label: Windows 10 22H2
        - label: Windows 10 21H2
        - label: Other (Please specify)
    validations:
      required: true
  - type: input
    attributes:
      label: Other Windows build number
      description: "Specify your Windows build number if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Intel System Support Utility report
      description: |
        Please generate and attach the output of Intel® System Support Utility here.

        See: [How to generate Intel System Support Utility report - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report)
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Description and steps to reproduce [Required]
      description: |
        Make sure you describe the issue and steps to reproduce accurately.
        
        In addition, if possible, please attach a video showing the issue.
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Device / Platform
      description: "Share your device / platform name. It could be there is a specific constructor issue. [Recommended]"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Crash dumps [Required, if applicable]               
      description: "For more help see: [How to obtain crash dumps - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-obtain-crash-dumps)"
      placeholder: |
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.

        Attach your compressed (*.zip*) dump here.
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Application / Windows logs
      description: "if available, could help solve the issue faster. [Optional]"
      placeholder: |
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.

        Attach your compressed (*.zip*) logs here.
