name: Feature request
description: Request a feature.
labels: 'Type: Feature Request'
assignees: 'Bryce-7995'
body:
  - type: input
    attributes:
      label:  Application [Required]
      description: "Full name of the application that requires the feature"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Processor / Processor Number [Required]
    validations:
      required: true
  - type: input
    attributes:
      label: Graphic Card [Required]
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Rendering API [Required]
      options:
        - label: Vulkan
        - label: OpenGL
        - label: DirectX12
        - label: DirectX11
        - label: DirectX10
        - label: DirectX9
        - label: Not applicable
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Windows Build Number [Required]
      options:
        - label: Windows 11 22H2
        - label: Windows 11 21H1 (*October 2021 Update*)
        - label: Windows 10 21H2 (*November 2021 Update*)
        - label: Windows 10 21H1 (*May 2021 Update*)
        - label: Windows 10 20H2 (*October 2020 Update*)
        - label: Windows 10 20H1 (*May 2020 Update*)
        - label: Other (Please specify)
    validations:
      required: true
  - type: input
    attributes:
      label: Other Windows build number
      description: "Specify your Windows build number if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Describe the feature [Required]
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Additional notes
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
